//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int PayrollID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<decimal> Bonus { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
