//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceReview
    {
        public int ReviewID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> ReviewerID { get; set; }
        public string Feedback { get; set; }
        public Nullable<decimal> Rating { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
